// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlvvzygtgmibcpeeuchp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsdnZ6eWd0Z21pYmNwZWV1Y2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3ODEyNzQsImV4cCI6MjA3NjM1NzI3NH0.JGA2F4p4IUSzZJRkzTmmeRLwNIk7N1ODxKnWUhlAuO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});